# Production configs
spring:
  jpa:
    show-sql: false
    hibernate.ddl-auto: none
    properties.hibernate.format_sql: false
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:file:~/product-api_db;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;MV_STORE=FALSE;MVCC=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yml

server.tomcat.max-threads: 20

fixerio:
  access-key: 62bc67dcbc99f2007bcc430064c7065d
  # This TTL configuration makes possible to use fixer-io free account in prod as it supports 1000 request per month.
  # You can force an update
  cache-eviction-minutes: 45
